Implmentation of 'Movie list' screen.
katyasokol94/MyApplication pull request #2
Opened 2020-11-29 17:48 UTC by katyasokol94

Added UI for 'Movie list' screen. Implemented navigation between fragments. 
File item_movie.xml was implemnted a UI for movie item at  'Movie list' screen, according to general logic at this screen will be a list, so for avoiding a wasting time for changing UI, I was added this element as separate layout but for current ui at Figma it should be just a simple view, so I copied UI logic from item_movie.xml.
![image](https://user-images.githubusercontent.com/73844872/100549250-f0adee80-3282-11eb-95de-9a1d421014ed.png)
![image](https://user-images.githubusercontent.com/73844872/100549306-44203c80-3283-11eb-8e5d-d0391a04b529.png)
![image](https://user-images.githubusercontent.com/73844872/100549473-299a9300-3284-11eb-9e6d-da15dc165fbd.png)

2020-11-29 21:52 UTC, PaulXIII requested changes

2020-11-29 21:52 UTC, PaulXIII commented on app/src/main/java/com/sokolkatya/myapplication/ui/MainActivity.kt
> +        supportFragmentManager.beginTransaction()
Здесь стоит добавить проверку для `savedInstanceState` в случае переворота экрана

2020-11-29 21:52 UTC, PaulXIII commented on app/src/main/java/com/sokolkatya/myapplication/ui/MainActivity.kt
> +    private fun removeLastFragment() {
Неплохая реализация)) Но уже есть встроенный `backStack` и лучше использовать его

2020-11-29 21:52 UTC, PaulXIII commented on app/src/main/res/drawable/bg_movie_item.xml
> +        android:endColor="#222232"
Значение стоит перенести в `colors.xml`

2020-11-29 21:52 UTC, PaulXIII commented on app/src/main/res/drawable/bg_movie_item.xml
> +        android:startColor="#FD404056"
Значение стоит перенести в `colors.xml`

2020-11-29 21:52 UTC, PaulXIII commented on app/src/main/res/drawable/ic_favorite.xml
> +    android:tint="#FFFFFF"
Значение стоит перенести в `colors.xml`

2020-11-29 21:52 UTC, PaulXIII commented on app/src/main/res/drawable/ic_movie_list.xml
> +        android:fillColor="#FFFFFF"
Значение стоит перенести в `colors.xml`

2020-11-29 21:52 UTC, PaulXIII commented on app/src/main/res/layout/fragment_movies_list.xml
> +        <androidx.constraintlayout.widget.ConstraintLayout
Возможно нет нужды в дополнительном `ConstraintLayout`

2020-12-01 17:20 UTC, katyasokol94 commented on app/src/main/res/layout/fragment_movies_list.xml
> +        <androidx.constraintlayout.widget.ConstraintLayout
Да, здесь действительно не нужен дополнительный `ConstraintLayout`, но из дизайна для этой части задания было видно, что будет `RecyclerView`, поэтому `layout` сразу делала в отдельном файле, и из-за нехватки времени просто скопировала весь `layout`, так как проще определить положение одного элемента, чем всех, тем более, что потом они будут переноситься в отдельный файл.

2020-12-01 21:22 UTC, PaulXIII approved these changes

2020-12-02 17:08 UTC, merged