Implement recyclerview
katyasokol94/MyApplication pull request #3
Opened 2020-12-05 21:09 UTC by katyasokol94

Implemented RecyclerView for both screens. For RecyclerView at 'Movie List' screen implemented logic of clicking at item and open of 'Movie details' screen.
![image](https://user-images.githubusercontent.com/73844872/101265309-6966ec00-3756-11eb-90b4-21b59b5ac5c5.png)
![image](https://user-images.githubusercontent.com/73844872/101265318-7683db00-3756-11eb-9e36-c43f57875a52.png)

2020-12-06 17:49 UTC, PaulXIII requested changes

2020-12-06 17:49 UTC, PaulXIII commented on app/src/main/res/layout/fragment_movies_list.xml
> +        android:layout_marginTop="56dp"
Размеры лучше вызывать через ресурсы

2020-12-08 18:32 UTC, katyasokol94 commented on app/src/main/res/layout/fragment_movies_list.xml
> +        android:layout_marginTop="56dp"
На мой взгляд, размеры не совсем удобно вызывать через ресурсы, так как в основном имеет место wrap_content/match_parent либо же 0dp, если это view в ConstraintLayout, числовые же значения используются для отступов, а здесь обычно достаточно большой разброс, что сводит на нет идею вынесения значений в ресурсы. Я имела дело с разными проектами, где размеры все были в ресурсах, что достаточно замедляло вёрстку, и там где напрямую использовались значения, и только значения для радиусов, так как там стараются придерживаться более менее стандартных значений, были вынесены в ресурсы, на мой взгляд удобнее в использовании второй вариант, так как ты держишь в памяти, что для радиусов у тебя есть значения, а для остальных ты волен использовать локально что тебе нужно.

2020-12-10 15:23 UTC, PaulXIII commented on app/src/main/res/layout/fragment_movies_list.xml
> +        android:layout_marginTop="56dp"
Но ведь здесь речь не про размеры в виде высоты или ширины, а о размере отступов. Их не получиться задать через `match_parent` или `wrap_content`. Отступы как правило имеют набор значений и их стоит выносить в ресурсы для повторного использования. Просто называть переменные для отображения отступов, например `margin_16=16dp``margin_18=18dp` и т.д.

2020-12-14 18:35 UTC, PaulXIII approved these changes

2020-12-15 19:00 UTC, merged