Implement load data
katyasokol94/MyApplication pull request #4
Opened 2020-12-17 19:47 UTC by katyasokol94

Implemented loading data for both screens. Also implemented logic of hiding 'Cast' label and list of 'Actors' if no actors in the received data.
![image](https://user-images.githubusercontent.com/73844872/102535060-b8971000-40b8-11eb-9f02-f0f9cbc33e49.png)
![image](https://user-images.githubusercontent.com/73844872/102535111-cc427680-40b8-11eb-99ae-0ff0ca849a35.png)
![image](https://user-images.githubusercontent.com/73844872/102535193-eda36280-40b8-11eb-8bf8-7f58621de1dd.png)

2020-12-19 11:18 UTC, PaulXIII requested changes

2020-12-19 11:18 UTC, PaulXIII commented on app/src/main/java/com/sokolkatya/myapplication/ui/movie_details/FragmentMoviesDetails.kt
> +        scope.cancel()
Отмену корутин лучше проводить в `onDestroyView`

2020-12-19 11:18 UTC, PaulXIII commented on app/src/main/java/com/sokolkatya/myapplication/ui/movie_list/FragmentMoviesList.kt
> +        scope.cancel()
Отмену корутин лучше проводить в `onDestroyView`

2020-12-21 19:51 UTC, katyasokol94 commented on app/src/main/java/com/sokolkatya/myapplication/ui/movie_details/FragmentMoviesDetails.kt
> +        scope.cancel()
А почему именно на это этапе жизненного цикла, а не в `onDestroy`? Только из-за того что `onDestroyView` отрабатывает раньше?

2020-12-22 08:25 UTC, PaulXIII approved these changes

2020-12-22 08:25 UTC, PaulXIII commented on app/src/main/java/com/sokolkatya/myapplication/ui/movie_details/FragmentMoviesDetails.kt
> +        scope.cancel()
В целом да. Поскольку `Fragment`, в отличии от `Activity`, имеет жизненный цикл View и жизненный цикл самого Fragment, то лучше всего делать отмену на стадии `onDestroyView` для ограничения доступа к View

2020-12-24 20:15 UTC, katyasokol94 commented on app/src/main/java/com/sokolkatya/myapplication/ui/movie_details/FragmentMoviesDetails.kt
> +        scope.cancel()
Ясно, спасибо за информацию.

2020-12-24 20:16 UTC, merged